version: '3'

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile      
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./app:/home/calendar/app
    environment:
      ICS_URL: ${ICS_URL}
    tty: true 